### ISSUE TITLE
Remove `<b>` in `<dt>`

### ISSUE THREAD

**Issue by palemieux** [SMPTE/ag-02#3]
`<dt><b>Spreadsheet:</b> .xls and .xlsx</dt>`

should be

`<dt>Spreadsheet: .xls and .xlsx</dt>`

since 

*  `<dt>` is already rendered with emphasis
*  The contents of `<dt>` should really only be _Spreadsheet_ with the `dl` defining what it means

**Comment by dcbullock** [comment]
The html-pub on tip of main, does not seem to provide any emphasis for `<dt>`.  Maybe that's in a branch.

I will move the extraneous `<dt>` contents to a new paragraph in the `<dd>`.  This will look different that the PDF, but all of our `<dl>`s do.  It will still produce the same redline from Word for me because I am skipping whitespace in the Word compare dialog.

**Comment by dcbullock** [comment]
Fixed in [55c8539](https://github.com/SMPTE/ag-02/commit/55c85391df61cf1b85e7c5c165f8e8f3fc50190f).

**Comment by SteveLLamb** [comment]
This is changed now, closing.
